import 'shared/styles/app.scss'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import Header from '../../templates/_layout/Header/Header'
import ShootoutProvider from 'templates/shootout/providers/ShootoutContext'

const geistSans = Geist({
  weight: ['400', '700', '900'],
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={geistSans.className}>
      <body>
        <ShootoutProvider>
          <Header />
          {children}
        </ShootoutProvider>
      </body>
    </html>
  )
}
